### ISSUE TITLE
Java UUID Support

### ISSUE THREAD

**Issue by raceconditions** [reinert/JJSchema#39]
Awesome library!  I'm using JJSchema to generate schemas to be validated by https://github.com/fge/json-schema-validator.  [fge/json-schema-validator](https://github.com/fge/json-schema-validator).  That library expects UUID to have a format property of "uuid" and type String.  I have made a few tiny modifications locally, and will submit a pull request against this issue.

**Comment by reinert** [comment]
Great! Thanks!
