### ISSUE TITLE
Latest Code on Maven repository

### ISSUE THREAD

**Issue by nowke** [reinert/JJSchema#50]
When can we expect the version `1.0` or `0.9-SNAPSHOT` on Maven repo?

**Comment by seanstaley** [comment]
@reinert, do you have any plans on moving this code to maven for a release in the near future. You have some fixes in the latest code that I have needed for a few years now. Specifically NullPointerExceptions that have now been resolved.

Thanks!

**Comment by reinert** [comment]
I'll try to do that this week.

**Comment by reinert** [comment]
JJSchema 1.0 deployed.

In a few hours it may be available at maven central.

**Comment by seanstaley** [comment]
Thanks sir!

**Comment by reinert** [comment]
I just checked, JJSchema 1.0 is already at maven central.
Sorry you all for the long delay.
I promise releases will be done more frequently now on.
Contribuitions are always welcome.
Thanks!
