### ISSUE TITLE
Using $ref

### ISSUE THREAD

**Issue by cilogi** [reinert/JJSchema#53]
Given the following

```
class A {
    Opaque ref;
}

class Opaque {
    int val;
}
```

I'd like to get something like:

```
{
    "type": "object",
    "properties": {
        "ref" {
            "$ref": "some reference"
        }
    }
}
```

as a schema for `class A` by using an annotation on class A's `ref` property.  the following doesn't work

```
class A {
    @Attributes($ref = "some reference")
    Opaque ref;
}
```

as it still includes the schema for class `Opaque`. Is there some way to get what I want?

**Comment by magick93** [comment]
This is an interesting question.

Why was it closed?
