### ISSUE TITLE
How to generate the JSON schema for List<Product>

### ISSUE THREAD

**Issue by TianhongZhang** [reinert/JJSchema#54]
This is not an issue, but a question. The Product example shown in the README works nicely for simple class. How do I generate the JSON schema for a list of Product?
Thanks

**Comment by reinert** [comment]
To achieve that, you must wrap the Collection into a class.

See: https://github.com/reinert/JJSchema/blob/master/src/test/java/com/github/reinert/jjschema/model/Users.java

**Comment by TianhongZhang** [comment]
This will generate a top level type of "object", but I would like to have a top level type of "array".

**Comment by dkar-reply** [comment]
```
public static JsonNode getJsonSchemaForClass(Class<?> clazz) throws JsonProcessingException {
     ObjectNode jNode = mapper.createObjectNode();
     jNode.put("type", "array");
     jNode.put(clazz.getSimpleName().toLowerCase(), getJsonSchema(clazz));
     return jNode;
}
```
@TianhongZhang I guess this can help you out. I tried this way around for a project of mine.
