### ISSUE TITLE
Restrict depth of properties

### ISSUE THREAD

**Issue by rdgupt** [reinert/JJSchema#58]
Hi, it is a question, not an issue.
Is it possible to restrict how deep Json Schema should be generated?
For example, there is a class User, which has a custom class as it's property called Organisation. Now Organisation has further more CustomClasses as it's properties.
Can we restrict the generated Schema to list only properties of User, and not list Properties of Organisation in Json schema of User?
Just list Organisation as type:object+some other details, but not go in the iteration of properties of all nth great grand children. Hope question is clear. :)

Thanks, Rishi

**Comment by reinert** [comment]
Yeah, that's possible.
Just put `@SchemaIgnore` on top of the field you want to bypass.
See this [test](https://github.com/reinert/JJSchema/blob/2fb5fbc21fd5493da17ce8182935d07f4bb0c7d8/src/test/java/com/github/reinert/jjschema/v1/SchemaIgnoreTest.java).

**Comment by rdgupt** [comment]
I don't want to completely bypass the object. I only want to bypass it's properties.
For example, let us extend the Product example and add a property catalog to it, which is a class (with some props).
	@Attributes(required = true)
	private Catalog catalog;

When we generate Json schema of Product class, it should list catalog in properties of Product, but should not show properties of catalog in json schema of Prodct.
like this : "catalog":{"type":"object"}"
and not like this : "catalog":{"type":"object","properties":{"..."}}

Let me know if that is possible or any plans for the enhancement.

**Comment by reinert** [comment]
I see. That's not possible yet. But I believe it's not difficult to implement. I could take a look at it this week to tell you if I can work on it. But I really prefer contributions, as this is a collaborative project. If you think you can contribute, please don't hesitate.

**Comment by rdgupt** [comment]
Thanks Danilo.

**Comment by reinert** [comment]
This issue is solved by the new annotation `@SchemaIgnoreProperties`.
