### ISSUE TITLE
Add support to versioned JSON schema validation

### ISSUE THREAD

**Issue by greggvarona** [reinert/JJSchema#59]
Hi. I would like to ask if there are plans in the future to add support for versioned schema? In our case, we use JJSchema for schema validation in our REST API. We want to maintain a single resource (model/class) that can potentially have different schema for different API versions rather than implement a new resource for every new API version.

**Comment by reinert** [comment]
Hi. I'm really not able to evolve the project on my own. If there is interest in actively developing it, I can enable new committers.
