### ISSUE TITLE
Dynamic Schema support

### ISSUE THREAD

**Issue by vladimirghetau** [reinert/JJSchema#69]
Does JJSchema support dynamic schema? ty.

**Comment by reinert** [comment]
Hi, sorry for the delay. (vacation...)

I'm not sure what you mean by "dynamic schema" but jjschema doesn't have such feature.

It aims to create a json schema from a java class, nothing more than that.

**Comment by heat** [comment]
Also a resource must be well defined.
Requesting `/api/fruit/apple` and get a `orange` schema instead wouldn't be fine.
