### ISSUE TITLE
java.util.Date serializing and deserializing

### ISSUE THREAD

**Issue by ghassen1khalil** [reinert/JJSchema#80]
Generating json from a Date attribute in a Pojo gives : 
updateDate :  {
    "time": number,
    "year": number,
    "hours": number,
    "seconds": number,
    "timezoneOffset": number,
    "day": number,
    "minutes": number,
    "date": number,
    "month": number
  }

When I try to create an instance of my Pojo I use the same structure but it gives me an com.fasterxml.jackson.databind.JsonMappingException with a message saying : Can not deserialize instance of java.util.Date out of START_OBJECT token \n

**Comment by reinert** [comment]
Fixed in https://github.com/reinert/JJSchema/commit/2d92e5e55292ba0b574ba46f8ef49b079ffb8e2d.

Thanks for reporting.
