### ISSUE TITLE
Could you please change the minimum data range so that could be less than -1 

### ISSUE THREAD

**Issue by BeFabulousJia12** [reinert/JJSchema#86]
In **JJSchemaUtil.java** file, please change the data range condition for attributes.minimum() to make it possible be less than -1. Sometimes, we need set the minimum value e.g. -10, which is less than -1.
···
if (attributes.minimum() > -1) {
            node.put("minimum", attributes.minimum());
        }
···

**Comment by reinert** [comment]
Sure, I'll set Integer.MIN_VALUE

**Comment by reinert** [comment]
Solved in https://github.com/reinert/JJSchema/commit/1a25434f8f50161f7aef53b8bc1e1da6ff988f5d.

New version released.
