### ISSUE TITLE
Question: object mapper with custom configuration for schema generation

### ISSUE THREAD

**Issue by valasatava** [reinert/JJSchema#96]
Is it possible to provide custom configuration for object mapper used for schema generation?

**Comment by reinert** [comment]
Yes, you can directly access the ObjectMapper responsible for generating the schemes through `SchemaWrapperFactory .MAPPER`. Be careful, though, to use `JsonSchemaV4Factory` instead of `JsonSchemaGeneratorV4` which is deprecated.

**Comment by valasatava** [comment]
it doesn't seem to work with 
<code>
SchemaWrapperFactory.MAPPER.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
<code>
my interest in having a lower underscore case format in the resulting JSON schema.

**Comment by reinert** [comment]
Please, post your code so I can tell you better what to do.

**Comment by valasatava** [comment]
Sorry it took me so long to provide more information. Here is my code:

{code}
        JsonSchemaFactory schemaFactory = new JsonSchemaV4Factory();
        schemaFactory.setAutoPutDollarSchema(true);
        JsonNode schema = schemaFactory.createSchema(Entry.class);
{code}

I'd linke to configure the mapper to use snake case naming strategy.

**Comment by reinert** [comment]
Where is your mapper?

**Comment by reinert** [comment]
If you're using JAX-RS with some Jackson integration, than you need to configure the mapper based on Jackson's jax-rs docs.

**Comment by valasatava** [comment]
It's a simple Java application with dependences on Jackson libraries. I can create and configure the mapper but it seems that JsonSchemaV4Factory relies on the mapper internally. What's the mechanism to alter it's behavior?

**Comment by reinert** [comment]
I see. It seems Jackson converts only Java POJOs to configured case but doesn't behavior similarly with JsonNodes (and other objects).

JJSchema produces JsonNodes in camel case by default. The generated JsonNode should be converted to snake case manually or with some other library like guava or gson.

Please refer to this [SO thread](https://stackoverflow.com/questions/30727417/jackson-json-to-map-and-camelcase-key-name) for a deeper explanation.

**Comment by valasatava** [comment]
Thank you very much for you prompt responses and references. I'll proceed from there.

**Comment by reinert** [comment]
As a test execute the following code:
```java
ObjectMapper MAPPER = new ObjectMapper();
MAPPER.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);

ObjectNode node = MAPPER.createObjectNode();
node.put("camelCase", "test");

System.out.println(MAPPER.writeValueAsString(node));
```

and it will produce:
`{"camelCase":"test"}`
