### ISSUE TITLE
Removing guava dependency

### ISSUE THREAD

**Issue by matejsp** [reinert/JJSchema#97]
It is used only for one call with concatenation of two arrays and new ArrayList<>() with calling the method that will soon be deprecated according to javadoc. I prefer libraries to keep list of dependencies to a minimum.

It's really easy to replace the code with couple of lines (instead of 2.6 MB dependency):
```
	public static <E> ArrayList<E> newArrayListWithExpectedSize(int estimatedSize) {
	    return new ArrayList<>(5 + estimatedSize + (estimatedSize / 10));
	}

	public static <T> T[] concat(T[] first, T[] second, Class<T> type) {
		T[] result = (T[])new Object[first.length + second.length];
		System.arraycopy(first, 0, result, 0, first.length);
		System.arraycopy(second, 0, result, first.length, second.length);
		return result;
	}
```

**Comment by reinert** [comment]
Thanks, I'll make that change.

**Comment by reinert** [comment]
Version 1.15 is now published with the changes you requested.
